baseURL = "https://geikogroove.github.io/"
languageCode = "fr-fr"
title = "Geiko Groove"
theme = "minimal"
googleAnalytics = ""

[params]
    author = "Masao Sette"
    description = "Feminist musical band for love"
    githubUsername = "epehj"
    accent = "white"
    showBorder = false
    backgroundColor = "black"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = false
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
	color = "white"

[[menu.main]]
    url = "/accueil"
    name = "Accueil"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "À Propos"
    weight = 2

[[menu.main]]
    url = "/medias/"
    name = "Medias"
    weight = 3

[[menu.main]]
    url = "/contact/"
    name = "Contact"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:geishagroove.event@gmail.com"
    name = "fa fa-envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://soundcloud.com/geikogroove/"
    name = "fab fa-soundcloud"
    weight = 2

[[menu.icon]]
    url = "https://spotify.com/geikogroove/"
    name = "fab fa-spotify"
    weight = 3

[[menu.icon]]
    url = "https://www.itunes/"
    name = "fab fa-itunes-note"
    weight = 4
